---------------------------------------------------------------------
--  ACCÈS À LA BASE
---------------------------------------------------------------------

GRANT CONNECT ON DATABASE ige487_65db TO ige487_10;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_36;

GRANT CONNECT ON DATABASE ige487_65db TO ige487_61;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_62;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_63;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_64;
/* 65 exclu */
GRANT CONNECT ON DATABASE ige487_65db TO ige487_66;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_67;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_68;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_69;
GRANT CONNECT ON DATABASE ige487_65db TO ige487_70;

---------------------------------------------------------------------
--  SCHÉMA Herbivorie  (PAS DE SELECT – SEULEMENT USAGE + EXECUTE)
---------------------------------------------------------------------

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_10;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_10;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_10;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_10;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_36;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_36;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_36;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_36;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_61;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_61;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_61;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_61;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_62;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_62;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_62;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_62;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_63;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_63;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_63;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_63;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_64;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_64;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_64;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_64;

/* 65 EXCLU */

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_66;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_66;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_66;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_66;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_67;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_67;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_67;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_67;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_68;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_68;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_68;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_68;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_69;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_69;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_69;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_69;

GRANT USAGE ON SCHEMA "Herbivorie" TO ige487_70;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie" TO ige487_70;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie" TO ige487_70;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie" FROM ige487_70;


---------------------------------------------------------------------
--  SCHÉMA Herbivorie_lecture (IMM – EVA)
--  USAGE + EXECUTE SEULEMENT (pas de SELECT)
---------------------------------------------------------------------

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_10;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_10;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_10;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_10;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_36;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_36;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_36;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_36;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_61;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_61;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_61;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_61;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_62;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_62;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_62;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_62;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_63;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_63;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_63;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_63;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_64;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_64;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_64;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_64;

/* 65 exclus */

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_66;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_66;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_66;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_66;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_67;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_67;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_67;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_67;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_68;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_68;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_68;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_68;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_69;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_69;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_69;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_69;

GRANT USAGE ON SCHEMA "Herbivorie_lecture" TO ige487_70;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "Herbivorie_lecture" TO ige487_70;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA "Herbivorie_lecture" TO ige487_70;
REVOKE SELECT ON ALL TABLES IN SCHEMA "Herbivorie_lecture" FROM ige487_70;


