SET SCHEMA "Herbivorie";

DROP TABLE IF EXISTS ObsPrecipitations CASCADE;
DROP TABLE IF EXISTS TypePrecipitations CASCADE;

DROP TABLE IF EXISTS ObsPression CASCADE;
DROP TABLE IF EXISTS ObsVents CASCADE;
DROP TABLE IF EXISTS ObsHumidite CASCADE;
DROP TABLE IF EXISTS ObsTemperature CASCADE;

DROP TABLE IF EXISTS CarnetMeteo CASCADE;

DROP DOMAIN IF EXISTS Temperature CASCADE;
DROP DOMAIN IF EXISTS Humidite CASCADE;
DROP DOMAIN IF EXISTS Vitesse CASCADE;
DROP DOMAIN IF EXISTS Pression CASCADE;
DROP DOMAIN IF EXISTS HNP CASCADE;
DROP DOMAIN IF EXISTS Code_P CASCADE;

DROP TABLE IF EXISTS ObsEtat CASCADE;
DROP TABLE IF EXISTS Etat CASCADE;

DROP TABLE IF EXISTS ObsFloraison CASCADE;

DROP TABLE IF EXISTS ObsDimension CASCADE;

DROP TABLE IF EXISTS Plant CASCADE;

DROP TABLE IF EXISTS Parcelle CASCADE;

DROP TABLE IF EXISTS Placette_Couvert CASCADE;
DROP TABLE IF EXISTS Placette_Obstruction CASCADE;
DROP TABLE IF EXISTS Placette_Dominant CASCADE;
DROP TABLE IF EXISTS Placette_Core CASCADE;

DROP TABLE IF EXISTS Placette CASCADE;

DROP TABLE IF EXISTS Unite CASCADE;

DROP TABLE IF EXISTS Taux CASCADE;

DROP TABLE IF EXISTS Arbre CASCADE;
DROP TABLE IF EXISTS Peuplement CASCADE;

DROP TABLE IF EXISTS Zone CASCADE;
DROP TABLE IF EXISTS Site CASCADE;

DROP TYPE IF EXISTS Ttaux CASCADE;
DROP TYPE IF EXISTS obstruction_nature CASCADE;
DROP TYPE IF EXISTS hauteur_obs CASCADE;
DROP TYPE IF EXISTS couvert_type CASCADE;
DROP TYPE IF EXISTS unite_mesure CASCADE;

DROP DOMAIN IF EXISTS Arbre_id CASCADE;
DROP DOMAIN IF EXISTS Description CASCADE;
DROP DOMAIN IF EXISTS Peuplement_id CASCADE;
DROP DOMAIN IF EXISTS Dim_mm CASCADE;
DROP DOMAIN IF EXISTS Placette_id CASCADE;
DROP DOMAIN IF EXISTS Date_eco CASCADE;
DROP DOMAIN IF EXISTS rang CASCADE;
DROP DOMAIN IF EXISTS unite_id CASCADE;
DROP DOMAIN IF EXISTS Taux_val CASCADE;
DROP DOMAIN IF EXISTS Plant_id CASCADE;
DROP DOMAIN IF EXISTS Parcelle_id CASCADE;
DROP DOMAIN IF EXISTS Etat_id CASCADE;
DROP DOMAIN IF EXISTS Site_id CASCADE;
DROP DOMAIN IF EXISTS Zone_id CASCADE;

DROP TRIGGER IF EXISTS trg_check_tval_obstruction ON Placette_Obstruction CASCADE;
DROP TRIGGER IF EXISTS trg_check_tval_couvert ON Placette_Couvert CASCADE;

DROP FUNCTION IF EXISTS check_tval_in_taux_bounds() CASCADE;
DROP FUNCTION IF EXISTS verif_pression_vent() CASCADE;

DELETE FROM ObsPrecipitations;
DELETE FROM TypePrecipitations;
DELETE FROM ObsPression;
DELETE FROM ObsVents;
DELETE FROM ObsHumidite;
DELETE FROM ObsTemperature;
DELETE FROM CarnetMeteo;

DELETE FROM ObsEtat;
DELETE FROM Etat;

DELETE FROM ObsFloraison;
DELETE FROM ObsDimension;
DELETE FROM Plant;

DELETE FROM Parcelle;

DELETE FROM Placette_Couvert;
DELETE FROM Placette_Obstruction;
DELETE FROM Placette_Dominant;
DELETE FROM Placette_Core;

DELETE FROM Placette;

DELETE FROM Unite;
DELETE FROM Taux;
DELETE FROM Arbre;
DELETE FROM Peuplement;

DELETE FROM Zone;
DELETE FROM Site;
